require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
Hc/RailsSpecificActionName:
  Enabled: false
Metrics/BlockLength:
  Max: 30
Metrics/MethodLength:
  Max: 20
Layout/LineLength:
  Max: 200