require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Max: 31
Metrics/MethodLength:
  Max: 34
Layout/LineLength:
  Max: 200
Metrics/AbcSize:
  Max: 30